feat: add complete support for multi-line scripts (#834)

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -64,10 +64,66 @@ jobs:
         with:
           working-directory: target
           should-run-codecov: false
+  failure-tests:
+    runs-on: ubuntu-24.04
+    steps:
+      - name: Checkout the Gradle wrapper
+        uses: actions/checkout@v4.2.2
+        with:
+          repository: DanySK/gradle-wrapper
+      - name: Checkout
+        uses: actions/checkout@v4.2.2
+        with:
+          path: 'action'
+      - uses: ./action
+        id: just-false
+        continue-on-error: true
+        env:
+          ATTEMPT: "0"
+        with:
+          build-command: |
+            ATTEMPT=$( [ -f just-false ] && cat just-false || echo "0" )
+            ATTEMPT=$((ATTEMPT + 1))
+            echo "Attempt: $ATTEMPT"
+            echo "$ATTEMPT" > just-false
+            false
+          check-command: true
+          should-validate-wrapper: false
+          enable-cache: false
+          should-run-codecov: false
+      - uses: ./action
+        continue-on-error: true
+        id: false-true
+        with:
+          build-command: |
+            ATTEMPT=$( [ -f false-true ] && cat false-true || echo "0" )
+            ATTEMPT=$((ATTEMPT + 1))
+            echo "Attempt: $ATTEMPT"
+            echo "$ATTEMPT" > false-true
+            false
+            true
+          check-command: true
+          should-validate-wrapper: false
+          enable-cache: false
+          should-run-codecov: false
+      - name: Result
+        if: always()
+        run: |
+          [ '${{ steps.just-false.outcome}}' = 'failure' ]
+          echo "just-false failed successfully"
+          echo "It ran for $(cat just-false) attempts, they should be 2"
+          [ "$(cat just-false)" = '2' ]
+          echo "they are."
+          [ '${{ steps.false-true.outcome}}' = 'failure' ]
+          echo "false-true failed successfully"
+          echo "It ran for $(cat false-true) attempts, they should be 2"
+          [ "$(cat false-true)" = '2' ]
+          echo "they are."
   release:
     if: github.event_name == 'push'
     needs:
       - test
+      - failure-tests
     runs-on: ubuntu-24.04
     steps:
       - name: Checkout
diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -161,45 +161,74 @@ runs:
         key: ${{ runner.os }}-konan-${{ hashFiles('**/gradle/**.versions.toml', '**/**.gradle.kts') }}
         restore-keys: |
           ${{ runner.os }}-konan-
+    - name: UUID generation
+      shell: bash
+      id: uuid
+      run: echo "uuid=$(uuidgen)" >> $GITHUB_OUTPUT
     - name: Pre-build
       working-directory: ${{ inputs.working-directory }}
       shell: bash
       run: |
         echo "::group::Pre-Build"
+        # Strategy: create a file containing the step and prefixed with set -e
+
+        # This is the file header
+        echo "#!/bin/bash" > .${{ steps.uuid.outputs.uuid }}.sh
+        echo "set -e" >> .${{ steps.uuid.outputs.uuid }}.sh
+
+        # The file content is taken from the inputs. Note the single-quoted here-doc.
+        cat <<'${{ steps.uuid.outputs.uuid }}' >> .${{ steps.uuid.outputs.uuid }}.sh
+        ${{ inputs.pre-build-command }}
+        ${{ steps.uuid.outputs.uuid }}
+
+        # Make the file executable
+        chmod +x .${{ steps.uuid.outputs.uuid }}.sh
+
+        # Retry the command as needed
         for attempt in $(seq 1 "${{ inputs.retries-on-failure}}"); do
           echo "Attempt $attempt/${{ inputs.retries-on-failure }}"
-          {
-            ${{ inputs.pre-build-command }}
-          } && break || sleep "${{ inputs.wait-between-retries }}"
+          bash .${{ steps.uuid.outputs.uuid }}.sh && break || sleep "${{ inputs.wait-between-retries }}"
           if [ "$attempt" = "${{ inputs.retries-on-failure}}" ]; then false; fi
         done
+
+        # Cleanup
+        rm .${{ steps.uuid.outputs.uuid }}.sh
         echo "::endgroup::"
     - name: Build
       shell: bash
       working-directory: ${{ inputs.working-directory }}
       run: |
         echo "::group::Build"
-        COMMAND='${{ inputs.build-command }}'
+        echo "#!/bin/bash" > .${{ steps.uuid.outputs.uuid }}.sh
+        echo "set -e" >> .${{ steps.uuid.outputs.uuid }}.sh
+        cat <<'${{ steps.uuid.outputs.uuid }}' >> .${{ steps.uuid.outputs.uuid }}.sh
+        ${{ inputs.build-command }}
+        ${{ steps.uuid.outputs.uuid }}
+        chmod +x .${{ steps.uuid.outputs.uuid }}.sh
         for attempt in $(seq 1 "${{ inputs.retries-on-failure}}"); do
           echo "Attempt $attempt/${{ inputs.retries-on-failure }}"
-          {
-            ${{ inputs.build-command }}
-          } && break || sleep "${{ inputs.wait-between-retries }}"
+          bash .${{ steps.uuid.outputs.uuid }}.sh && break || sleep "${{ inputs.wait-between-retries }}"
           if [ "$attempt" = "${{ inputs.retries-on-failure}}" ]; then false; fi
         done
+        rm .${{ steps.uuid.outputs.uuid }}.sh
         echo "::endgroup::"
     - name: Check
       shell: bash
       working-directory: ${{ inputs.working-directory }}
       run: |
         echo "::group::Check"
+        echo "#!/bin/bash" > .${{ steps.uuid.outputs.uuid }}.sh
+        echo "set -e" >> .${{ steps.uuid.outputs.uuid }}.sh
+        cat <<'${{ steps.uuid.outputs.uuid }}' >> .${{ steps.uuid.outputs.uuid }}.sh
+        ${{ inputs.check-command }}
+        ${{ steps.uuid.outputs.uuid }}
+        chmod +x .${{ steps.uuid.outputs.uuid }}.sh
         for attempt in $(seq 1 "${{ inputs.retries-on-failure}}"); do
           echo "Attempt $attempt/${{ inputs.retries-on-failure }}"
-          {
-            ${{ inputs.check-command }}
-          } && break || sleep "${{ inputs.wait-between-retries }}"
+          bash .${{ steps.uuid.outputs.uuid }}.sh && break || sleep "${{ inputs.wait-between-retries }}"
           if [ "$attempt" = "${{ inputs.retries-on-failure}}" ]; then false; fi
         done
+        rm .${{ steps.uuid.outputs.uuid }}.sh
         echo "::endgroup::"
     - name: Check codecov token
       shell: bash
@@ -240,13 +269,18 @@ runs:
         ORG_GRADLE_PROJECT_npmToken: ${{ inputs.npm-token }}
       run: |
         echo "::group::Deploy"
+        echo "#!/bin/bash" > .${{ steps.uuid.outputs.uuid }}.sh
+        echo "set -e" >> .${{ steps.uuid.outputs.uuid }}.sh
+        cat <<'${{ steps.uuid.outputs.uuid }}' >> .${{ steps.uuid.outputs.uuid }}.sh
+        ${{ inputs.deploy-command }}
+        ${{ steps.uuid.outputs.uuid }}
+        chmod +x .${{ steps.uuid.outputs.uuid }}.sh
         for attempt in $(seq 1 "${{ inputs.retries-on-failure}}"); do
           echo "Attempt $attempt/${{ inputs.retries-on-failure }}"
-          {
-            ${{ inputs.deploy-command }}
-          } && break || sleep "${{ inputs.wait-between-retries }}"
+          bash .${{ steps.uuid.outputs.uuid }}.sh && break || sleep "${{ inputs.wait-between-retries }}"
           if [ "$attempt" = "${{ inputs.retries-on-failure}}" ]; then false; fi
         done
+        rm .${{ steps.uuid.outputs.uuid }}.sh
         echo "::endgroup::"
     - name: Cleanup
       working-directory: ${{ inputs.working-directory }}
